/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: linguamind/linalg.i

package linalg

import "unsafe"
import _ "runtime/cgo"
import "sync"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

var _wrap_Swig_free_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Swig_free(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Swig_free_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func Swig_free(arg1 uintptr) {
	_swig_wrap_Swig_free(arg1)
}

var _wrap_Swig_malloc_linalg_041245bb11fa8c6a unsafe.Pointer

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_Swig_malloc_linalg_041245bb11fa8c6a, _swig_p)
	return
}
type SwigcptrVectori uintptr

func (p SwigcptrVectori) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVectori) SwigIsVectori() {
}

var _wrap_new_vectori__SWIG_0_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_new_vectori__SWIG_0() (base SwigcptrVectori) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_vectori__SWIG_0_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func NewVectori__SWIG_0() (_swig_ret Vectori) {
	return _swig_wrap_new_vectori__SWIG_0()
}

var _wrap_new_vectori__SWIG_1_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_new_vectori__SWIG_1(base int64) (_ SwigcptrVectori) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_vectori__SWIG_1_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func NewVectori__SWIG_1(arg1 int64) (_swig_ret Vectori) {
	return _swig_wrap_new_vectori__SWIG_1(arg1)
}

func NewVectori(a ...interface{}) Vectori {
	argc := len(a)
	if argc == 0 {
		return NewVectori__SWIG_0()
	}
	if argc == 1 {
		return NewVectori__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

var _wrap_vectori_size_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectori_size(base SwigcptrVectori) (_ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_size_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Size() (_swig_ret int64) {
	return _swig_wrap_vectori_size(arg1)
}

var _wrap_vectori_capacity_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectori_capacity(base SwigcptrVectori) (_ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_capacity_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Capacity() (_swig_ret int64) {
	return _swig_wrap_vectori_capacity(arg1)
}

var _wrap_vectori_reserve_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectori_reserve(base SwigcptrVectori, _ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_reserve_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Reserve(arg2 int64) {
	_swig_wrap_vectori_reserve(arg1, arg2)
}

var _wrap_vectori_isEmpty_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectori_isEmpty(base SwigcptrVectori) (_ bool) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_isEmpty_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectori) IsEmpty() (_swig_ret bool) {
	return _swig_wrap_vectori_isEmpty(arg1)
}

var _wrap_vectori_clear_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectori_clear(base SwigcptrVectori) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_clear_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Clear() {
	_swig_wrap_vectori_clear(arg1)
}

var _wrap_vectori_add_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectori_add(base SwigcptrVectori, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_add_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Add(arg2 int) {
	_swig_wrap_vectori_add(arg1, arg2)
}

var _wrap_vectori_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectori_get(base SwigcptrVectori, _ int) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Get(arg2 int) (_swig_ret int) {
	return _swig_wrap_vectori_get(arg1, arg2)
}

var _wrap_vectori_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectori_set(base SwigcptrVectori, _ int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Set(arg2 int, arg3 int) {
	_swig_wrap_vectori_set(arg1, arg2, arg3)
}

var _wrap_delete_vectori_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_delete_vectori(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_vectori_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func DeleteVectori(arg1 Vectori) {
	_swig_wrap_delete_vectori(arg1.Swigcptr())
}

type Vectori interface {
	Swigcptr() uintptr
	SwigIsVectori()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 int)
	Get(arg2 int) (_swig_ret int)
	Set(arg2 int, arg3 int)
}

type SwigcptrVectorf uintptr

func (p SwigcptrVectorf) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVectorf) SwigIsVectorf() {
}

var _wrap_new_vectorf__SWIG_0_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_new_vectorf__SWIG_0() (base SwigcptrVectorf) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_vectorf__SWIG_0_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func NewVectorf__SWIG_0() (_swig_ret Vectorf) {
	return _swig_wrap_new_vectorf__SWIG_0()
}

var _wrap_new_vectorf__SWIG_1_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_new_vectorf__SWIG_1(base int64) (_ SwigcptrVectorf) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_vectorf__SWIG_1_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func NewVectorf__SWIG_1(arg1 int64) (_swig_ret Vectorf) {
	return _swig_wrap_new_vectorf__SWIG_1(arg1)
}

func NewVectorf(a ...interface{}) Vectorf {
	argc := len(a)
	if argc == 0 {
		return NewVectorf__SWIG_0()
	}
	if argc == 1 {
		return NewVectorf__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

var _wrap_vectorf_size_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectorf_size(base SwigcptrVectorf) (_ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectorf_size_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectorf) Size() (_swig_ret int64) {
	return _swig_wrap_vectorf_size(arg1)
}

var _wrap_vectorf_capacity_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectorf_capacity(base SwigcptrVectorf) (_ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectorf_capacity_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectorf) Capacity() (_swig_ret int64) {
	return _swig_wrap_vectorf_capacity(arg1)
}

var _wrap_vectorf_reserve_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectorf_reserve(base SwigcptrVectorf, _ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectorf_reserve_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectorf) Reserve(arg2 int64) {
	_swig_wrap_vectorf_reserve(arg1, arg2)
}

var _wrap_vectorf_isEmpty_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectorf_isEmpty(base SwigcptrVectorf) (_ bool) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectorf_isEmpty_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectorf) IsEmpty() (_swig_ret bool) {
	return _swig_wrap_vectorf_isEmpty(arg1)
}

var _wrap_vectorf_clear_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectorf_clear(base SwigcptrVectorf) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectorf_clear_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectorf) Clear() {
	_swig_wrap_vectorf_clear(arg1)
}

var _wrap_vectorf_add_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectorf_add(base SwigcptrVectorf, _ float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectorf_add_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectorf) Add(arg2 float32) {
	_swig_wrap_vectorf_add(arg1, arg2)
}

var _wrap_vectorf_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectorf_get(base SwigcptrVectorf, _ int) (_ float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectorf_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectorf) Get(arg2 int) (_swig_ret float32) {
	return _swig_wrap_vectorf_get(arg1, arg2)
}

var _wrap_vectorf_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectorf_set(base SwigcptrVectorf, _ int, _ float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectorf_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectorf) Set(arg2 int, arg3 float32) {
	_swig_wrap_vectorf_set(arg1, arg2, arg3)
}

var _wrap_delete_vectorf_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_delete_vectorf(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_vectorf_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func DeleteVectorf(arg1 Vectorf) {
	_swig_wrap_delete_vectorf(arg1.Swigcptr())
}

type Vectorf interface {
	Swigcptr() uintptr
	SwigIsVectorf()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 float32)
	Get(arg2 int) (_swig_ret float32)
	Set(arg2 int, arg3 float32)
}

type SwigcptrVectord uintptr

func (p SwigcptrVectord) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVectord) SwigIsVectord() {
}

var _wrap_new_vectord__SWIG_0_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_new_vectord__SWIG_0() (base SwigcptrVectord) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_vectord__SWIG_0_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func NewVectord__SWIG_0() (_swig_ret Vectord) {
	return _swig_wrap_new_vectord__SWIG_0()
}

var _wrap_new_vectord__SWIG_1_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_new_vectord__SWIG_1(base int64) (_ SwigcptrVectord) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_vectord__SWIG_1_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func NewVectord__SWIG_1(arg1 int64) (_swig_ret Vectord) {
	return _swig_wrap_new_vectord__SWIG_1(arg1)
}

func NewVectord(a ...interface{}) Vectord {
	argc := len(a)
	if argc == 0 {
		return NewVectord__SWIG_0()
	}
	if argc == 1 {
		return NewVectord__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

var _wrap_vectord_size_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectord_size(base SwigcptrVectord) (_ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_size_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Size() (_swig_ret int64) {
	return _swig_wrap_vectord_size(arg1)
}

var _wrap_vectord_capacity_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectord_capacity(base SwigcptrVectord) (_ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_capacity_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Capacity() (_swig_ret int64) {
	return _swig_wrap_vectord_capacity(arg1)
}

var _wrap_vectord_reserve_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectord_reserve(base SwigcptrVectord, _ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_reserve_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Reserve(arg2 int64) {
	_swig_wrap_vectord_reserve(arg1, arg2)
}

var _wrap_vectord_isEmpty_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectord_isEmpty(base SwigcptrVectord) (_ bool) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_isEmpty_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectord) IsEmpty() (_swig_ret bool) {
	return _swig_wrap_vectord_isEmpty(arg1)
}

var _wrap_vectord_clear_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectord_clear(base SwigcptrVectord) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_clear_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Clear() {
	_swig_wrap_vectord_clear(arg1)
}

var _wrap_vectord_add_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectord_add(base SwigcptrVectord, _ float64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_add_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Add(arg2 float64) {
	_swig_wrap_vectord_add(arg1, arg2)
}

var _wrap_vectord_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectord_get(base SwigcptrVectord, _ int) (_ float64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Get(arg2 int) (_swig_ret float64) {
	return _swig_wrap_vectord_get(arg1, arg2)
}

var _wrap_vectord_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_vectord_set(base SwigcptrVectord, _ int, _ float64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Set(arg2 int, arg3 float64) {
	_swig_wrap_vectord_set(arg1, arg2, arg3)
}

var _wrap_delete_vectord_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_delete_vectord(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_vectord_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func DeleteVectord(arg1 Vectord) {
	_swig_wrap_delete_vectord(arg1.Swigcptr())
}

type Vectord interface {
	Swigcptr() uintptr
	SwigIsVectord()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 float64)
	Get(arg2 int) (_swig_ret float64)
	Set(arg2 int, arg3 float64)
}

type SwigcptrCharp uintptr

func (p SwigcptrCharp) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCharp) SwigIsCharp() {
}

var _wrap_new_charp_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_new_charp() (base SwigcptrCharp) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_charp_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func NewCharp() (_swig_ret Charp) {
	return _swig_wrap_new_charp()
}

var _wrap_delete_charp_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_delete_charp(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_charp_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func DeleteCharp(arg1 Charp) {
	_swig_wrap_delete_charp(arg1.Swigcptr())
}

var _wrap_charp_assign_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_charp_assign(base SwigcptrCharp, _ byte) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_charp_assign_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrCharp) Assign(arg2 byte) {
	_swig_wrap_charp_assign(arg1, arg2)
}

var _wrap_charp_value_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_charp_value(base SwigcptrCharp) (_ byte) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_charp_value_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrCharp) Value() (_swig_ret byte) {
	return _swig_wrap_charp_value(arg1)
}

var _wrap_charp_cast_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_charp_cast(base SwigcptrCharp) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_charp_cast_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrCharp) Cast() (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_charp_cast(arg1)
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_charp_frompointer_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_charp_frompointer(base string) (_ SwigcptrCharp) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_charp_frompointer_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func CharpFrompointer(arg1 string) (_swig_ret Charp) {
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return _swig_wrap_charp_frompointer(arg1)
}

type Charp interface {
	Swigcptr() uintptr
	SwigIsCharp()
	Assign(arg2 byte)
	Value() (_swig_ret byte)
	Cast() (_swig_ret string)
}

type SwigcptrVector uintptr

func (p SwigcptrVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVector) SwigIsVector() {
}

var _wrap_new_Vector_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_new_Vector(base int) (_ SwigcptrVector) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Vector_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func NewVector(arg1 int) (_swig_ret Vector) {
	return _swig_wrap_new_Vector(arg1)
}

var _wrap_Vector_size_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector_size_set(base SwigcptrVector, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector_size_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) SetSize(arg2 int) {
	_swig_wrap_Vector_size_set(arg1, arg2)
}

var _wrap_Vector_size_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector_size_get(base SwigcptrVector) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector_size_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) GetSize() (_swig_ret int) {
	return _swig_wrap_Vector_size_get(arg1)
}

var _wrap_Vector__data_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector__data_set(base SwigcptrVector, _ *float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector__data_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) SetX_data(arg2 *float32) {
	_swig_wrap_Vector__data_set(arg1, arg2)
}

var _wrap_Vector__data_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector__data_get(base SwigcptrVector) (_ *float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector__data_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) GetX_data() (_swig_ret *float32) {
	return _swig_wrap_Vector__data_get(arg1)
}

var _wrap_Vector_zero_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector_zero(base SwigcptrVector) (_ SwigcptrVector) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector_zero_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) Zero() (_swig_ret Vector) {
	return _swig_wrap_Vector_zero(arg1)
}

var _wrap_Vector_uniform_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector_uniform(base SwigcptrVector, _ uint64) (_ SwigcptrVector) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector_uniform_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) Uniform(arg2 uint64) (_swig_ret Vector) {
	return _swig_wrap_Vector_uniform(arg1, arg2)
}

var _wrap_Vector_get__SWIG_0_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector_get__SWIG_0(base SwigcptrVector) (_ SwigcptrVectorf) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector_get__SWIG_0_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) Get__SWIG_0() (_swig_ret Vectorf) {
	return _swig_wrap_Vector_get__SWIG_0(arg1)
}

var _wrap_Vector_get__SWIG_1_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector_get__SWIG_1(base SwigcptrVector, _ int) (_ float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector_get__SWIG_1_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) Get__SWIG_1(arg2 int) (_swig_ret float32) {
	return _swig_wrap_Vector_get__SWIG_1(arg1, arg2)
}

func (p SwigcptrVector) Get(a ...interface{}) interface{} {
	argc := len(a)
	if argc == 0 {
		return p.Get__SWIG_0()
	}
	if argc == 1 {
		return p.Get__SWIG_1(a[0].(int))
	}
	panic("No match for overloaded function call")
}

var _wrap_Vector_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector_set(base SwigcptrVector, _ int, _ float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) Set(arg2 int, arg3 float32) {
	_swig_wrap_Vector_set(arg1, arg2, arg3)
}

var _wrap_Vector_dot_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector_dot(base SwigcptrVector, _ uintptr) (_ float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector_dot_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) Dot(arg2 Vector) (_swig_ret float32) {
	return _swig_wrap_Vector_dot(arg1, arg2.Swigcptr())
}

var _wrap_Vector_doti_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector_doti(base SwigcptrVector, _ int, _ uintptr, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector_doti_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) Doti(arg2 int, arg3 Vector, arg4 Vector) {
	_swig_wrap_Vector_doti(arg1, arg2, arg3.Swigcptr(), arg4.Swigcptr())
}

var _wrap_Vector___getitem____SWIG_0_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector___getitem____SWIG_0(base SwigcptrVector, _ int) (_ float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector___getitem____SWIG_0_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) X__getitem____SWIG_0(arg2 int) (_swig_ret float32) {
	return _swig_wrap_Vector___getitem____SWIG_0(arg1, arg2)
}

var _wrap_Vector___getitem____SWIG_1_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector___getitem____SWIG_1(base SwigcptrVector, _ int, _ int) (_ float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector___getitem____SWIG_1_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) X__getitem____SWIG_1(arg2 int, arg3 int) (_swig_ret float32) {
	return _swig_wrap_Vector___getitem____SWIG_1(arg1, arg2, arg3)
}

func (p SwigcptrVector) X__getitem__(a ...interface{}) float32 {
	argc := len(a)
	if argc == 1 {
		return p.X__getitem____SWIG_0(a[0].(int))
	}
	if argc == 2 {
		return p.X__getitem____SWIG_1(a[0].(int), a[1].(int))
	}
	panic("No match for overloaded function call")
}

var _wrap_Vector___setitem___linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector___setitem__(base SwigcptrVector, _ int, _ float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector___setitem___linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) X__setitem__(arg2 int, arg3 float32) {
	_swig_wrap_Vector___setitem__(arg1, arg2, arg3)
}

var _wrap_Vector___len___linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Vector___len__(base SwigcptrVector) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Vector___len___linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrVector) X__len__() (_swig_ret int) {
	return _swig_wrap_Vector___len__(arg1)
}

var _wrap_delete_Vector_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_delete_Vector(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Vector_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func DeleteVector(arg1 Vector) {
	_swig_wrap_delete_Vector(arg1.Swigcptr())
}

type Vector interface {
	Swigcptr() uintptr
	SwigIsVector()
	SetSize(arg2 int)
	GetSize() (_swig_ret int)
	SetX_data(arg2 *float32)
	GetX_data() (_swig_ret *float32)
	Zero() (_swig_ret Vector)
	Uniform(arg2 uint64) (_swig_ret Vector)
	Get(a ...interface{}) interface{}
	Set(arg2 int, arg3 float32)
	Dot(arg2 Vector) (_swig_ret float32)
	Doti(arg2 int, arg3 Vector, arg4 Vector)
	X__getitem__(a ...interface{}) float32
	X__setitem__(arg2 int, arg3 float32)
	X__len__() (_swig_ret int)
}

type SwigcptrMatrix uintptr

func (p SwigcptrMatrix) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrMatrix) SwigIsMatrix() {
}

var _wrap_new_Matrix_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_new_Matrix(base int, _ int) (_ SwigcptrMatrix) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Matrix_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func NewMatrix(arg1 int, arg2 int) (_swig_ret Matrix) {
	return _swig_wrap_new_Matrix(arg1, arg2)
}

var _wrap_Matrix_rows_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Matrix_rows_set(base SwigcptrMatrix, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Matrix_rows_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrMatrix) SetRows(arg2 int) {
	_swig_wrap_Matrix_rows_set(arg1, arg2)
}

var _wrap_Matrix_rows_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Matrix_rows_get(base SwigcptrMatrix) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Matrix_rows_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrMatrix) GetRows() (_swig_ret int) {
	return _swig_wrap_Matrix_rows_get(arg1)
}

var _wrap_Matrix_cols_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Matrix_cols_set(base SwigcptrMatrix, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Matrix_cols_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrMatrix) SetCols(arg2 int) {
	_swig_wrap_Matrix_cols_set(arg1, arg2)
}

var _wrap_Matrix_cols_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Matrix_cols_get(base SwigcptrMatrix) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Matrix_cols_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrMatrix) GetCols() (_swig_ret int) {
	return _swig_wrap_Matrix_cols_get(arg1)
}

var _wrap_Matrix__data_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Matrix__data_set(base SwigcptrMatrix, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Matrix__data_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrMatrix) SetX_data(arg2 Std_vector_Sl_Vector_Sm__Sg_) {
	_swig_wrap_Matrix__data_set(arg1, arg2.Swigcptr())
}

var _wrap_Matrix__data_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Matrix__data_get(base SwigcptrMatrix) (_ SwigcptrStd_vector_Sl_Vector_Sm__Sg_) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Matrix__data_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrMatrix) GetX_data() (_swig_ret Std_vector_Sl_Vector_Sm__Sg_) {
	return _swig_wrap_Matrix__data_get(arg1)
}

var _wrap_Matrix_zero_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Matrix_zero(base SwigcptrMatrix) (_ SwigcptrMatrix) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Matrix_zero_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrMatrix) Zero() (_swig_ret Matrix) {
	return _swig_wrap_Matrix_zero(arg1)
}

var _wrap_Matrix___getitem___linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Matrix___getitem__(base SwigcptrMatrix, _ int) (_ SwigcptrVector) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Matrix___getitem___linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrMatrix) X__getitem__(arg2 int) (_swig_ret Vector) {
	return _swig_wrap_Matrix___getitem__(arg1, arg2)
}

var _wrap_Matrix___setitem___linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Matrix___setitem__(base SwigcptrMatrix, _ int, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Matrix___setitem___linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrMatrix) X__setitem__(arg2 int, arg3 Vector) {
	_swig_wrap_Matrix___setitem__(arg1, arg2, arg3.Swigcptr())
}

var _wrap_Matrix___len___linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Matrix___len__(base SwigcptrMatrix) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Matrix___len___linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrMatrix) X__len__() (_swig_ret int) {
	return _swig_wrap_Matrix___len__(arg1)
}

var _wrap_delete_Matrix_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_delete_Matrix(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Matrix_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func DeleteMatrix(arg1 Matrix) {
	_swig_wrap_delete_Matrix(arg1.Swigcptr())
}

type Matrix interface {
	Swigcptr() uintptr
	SwigIsMatrix()
	SetRows(arg2 int)
	GetRows() (_swig_ret int)
	SetCols(arg2 int)
	GetCols() (_swig_ret int)
	SetX_data(arg2 Std_vector_Sl_Vector_Sm__Sg_)
	GetX_data() (_swig_ret Std_vector_Sl_Vector_Sm__Sg_)
	Zero() (_swig_ret Matrix)
	X__getitem__(arg2 int) (_swig_ret Vector)
	X__setitem__(arg2 int, arg3 Vector)
	X__len__() (_swig_ret int)
}

type SwigcptrTensor uintptr

func (p SwigcptrTensor) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTensor) SwigIsTensor() {
}

var _wrap_new_Tensor__SWIG_0_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_new_Tensor__SWIG_0() (base SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Tensor__SWIG_0_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func NewTensor__SWIG_0() (_swig_ret Tensor) {
	return _swig_wrap_new_Tensor__SWIG_0()
}

var _wrap_new_Tensor__SWIG_1_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_new_Tensor__SWIG_1(base uintptr) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Tensor__SWIG_1_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func NewTensor__SWIG_1(arg1 Vectori) (_swig_ret Tensor) {
	return _swig_wrap_new_Tensor__SWIG_1(arg1.Swigcptr())
}

var _wrap_new_Tensor__SWIG_2_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_new_Tensor__SWIG_2(base int, _ int) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Tensor__SWIG_2_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func NewTensor__SWIG_2(arg1 int, arg2 int) (_swig_ret Tensor) {
	return _swig_wrap_new_Tensor__SWIG_2(arg1, arg2)
}

func NewTensor(a ...interface{}) Tensor {
	argc := len(a)
	if argc == 0 {
		return NewTensor__SWIG_0()
	}
	if argc == 1 {
		return NewTensor__SWIG_1(a[0].(Vectori))
	}
	if argc == 2 {
		return NewTensor__SWIG_2(a[0].(int), a[1].(int))
	}
	panic("No match for overloaded function call")
}

var _wrap_Tensor_shape_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_shape_set(base SwigcptrTensor, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_shape_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) SetShape(arg2 Vectori) {
	_swig_wrap_Tensor_shape_set(arg1, arg2.Swigcptr())
}

var _wrap_Tensor_shape_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_shape_get(base SwigcptrTensor) (_ SwigcptrVectori) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_shape_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) GetShape() (_swig_ret Vectori) {
	return _swig_wrap_Tensor_shape_get(arg1)
}

var _wrap_Tensor_ndims_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_ndims_set(base SwigcptrTensor, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_ndims_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) SetNdims(arg2 int) {
	_swig_wrap_Tensor_ndims_set(arg1, arg2)
}

var _wrap_Tensor_ndims_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_ndims_get(base SwigcptrTensor) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_ndims_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) GetNdims() (_swig_ret int) {
	return _swig_wrap_Tensor_ndims_get(arg1)
}

var _wrap_Tensor__data_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor__data_set(base SwigcptrTensor, _ *float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor__data_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) SetX_data(arg2 *float32) {
	_swig_wrap_Tensor__data_set(arg1, arg2)
}

var _wrap_Tensor__data_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor__data_get(base SwigcptrTensor) (_ *float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor__data_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) GetX_data() (_swig_ret *float32) {
	return _swig_wrap_Tensor__data_get(arg1)
}

var _wrap_Tensor_num_elements_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_num_elements_set(base SwigcptrTensor, _ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_num_elements_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) SetNum_elements(arg2 int64) {
	_swig_wrap_Tensor_num_elements_set(arg1, arg2)
}

var _wrap_Tensor_num_elements_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_num_elements_get(base SwigcptrTensor) (_ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_num_elements_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) GetNum_elements() (_swig_ret int64) {
	return _swig_wrap_Tensor_num_elements_get(arg1)
}

var _wrap_Tensor_seed_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_seed_set(base SwigcptrTensor, _ uint64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_seed_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) SetSeed(arg2 uint64) {
	_swig_wrap_Tensor_seed_set(arg1, arg2)
}

var _wrap_Tensor_seed_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_seed_get(base SwigcptrTensor) (_ uint64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_seed_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) GetSeed() (_swig_ret uint64) {
	return _swig_wrap_Tensor_seed_get(arg1)
}

var _wrap_Tensor_init_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_init(base SwigcptrTensor, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_init_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) Init(arg2 Vectori) {
	_swig_wrap_Tensor_init(arg1, arg2.Swigcptr())
}

var _wrap_Tensor_dotRow_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_dotRow(base SwigcptrTensor, _ uintptr, _ int) (_ float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_dotRow_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) DotRow(arg2 Tensor, arg3 int) (_swig_ret float32) {
	return _swig_wrap_Tensor_dotRow(arg1, arg2.Swigcptr(), arg3)
}

var _wrap_Tensor_addRowi_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_addRowi(base SwigcptrTensor, _ uintptr, _ int) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_addRowi_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) AddRowi(arg2 Tensor, arg3 int) (_swig_ret Tensor) {
	return _swig_wrap_Tensor_addRowi(arg1, arg2.Swigcptr(), arg3)
}

var _wrap_Tensor_sub_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_sub(base SwigcptrTensor, _ uintptr, _ uintptr) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_sub_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) Sub(arg2 Tensor, arg3 Tensor) (_swig_ret Tensor) {
	return _swig_wrap_Tensor_sub(arg1, arg2.Swigcptr(), arg3.Swigcptr())
}

var _wrap_Tensor_uniform_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_uniform(base SwigcptrTensor) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_uniform_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) Uniform() (_swig_ret Tensor) {
	return _swig_wrap_Tensor_uniform(arg1)
}

var _wrap_Tensor_zero_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_zero(base SwigcptrTensor) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_zero_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) Zero() (_swig_ret Tensor) {
	return _swig_wrap_Tensor_zero(arg1)
}

var _wrap_Tensor_get_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_get(base SwigcptrTensor, _ int) (_ float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_get_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) Get(arg2 int) (_swig_ret float32) {
	return _swig_wrap_Tensor_get(arg1, arg2)
}

var _wrap_Tensor_set_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_Tensor_set(base SwigcptrTensor, _ int, _ float32) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Tensor_set_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func (arg1 SwigcptrTensor) Set(arg2 int, arg3 float32) {
	_swig_wrap_Tensor_set(arg1, arg2, arg3)
}

var _wrap_delete_Tensor_linalg_041245bb11fa8c6a unsafe.Pointer

func _swig_wrap_delete_Tensor(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Tensor_linalg_041245bb11fa8c6a, _swig_p)
	return
}

func DeleteTensor(arg1 Tensor) {
	_swig_wrap_delete_Tensor(arg1.Swigcptr())
}

type Tensor interface {
	Swigcptr() uintptr
	SwigIsTensor()
	SetShape(arg2 Vectori)
	GetShape() (_swig_ret Vectori)
	SetNdims(arg2 int)
	GetNdims() (_swig_ret int)
	SetX_data(arg2 *float32)
	GetX_data() (_swig_ret *float32)
	SetNum_elements(arg2 int64)
	GetNum_elements() (_swig_ret int64)
	SetSeed(arg2 uint64)
	GetSeed() (_swig_ret uint64)
	Init(arg2 Vectori)
	DotRow(arg2 Tensor, arg3 int) (_swig_ret float32)
	AddRowi(arg2 Tensor, arg3 int) (_swig_ret Tensor)
	Sub(arg2 Tensor, arg3 Tensor) (_swig_ret Tensor)
	Uniform() (_swig_ret Tensor)
	Zero() (_swig_ret Tensor)
	Get(arg2 int) (_swig_ret float32)
	Set(arg2 int, arg3 float32)
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_Vector_Sm__Sg_ uintptr
type Std_vector_Sl_Vector_Sm__Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_Vector_Sm__Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

