# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_nlp', [dirname(__file__)])
        except ImportError:
            import _nlp
            return _nlp
        if fp is not None:
            try:
                _mod = imp.load_module('_nlp', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _nlp = swig_import_helper()
    del swig_import_helper
else:
    import _nlp
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _nlp.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _nlp.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _nlp.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _nlp.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _nlp.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _nlp.SwigPyIterator_equal(self, x)

    def copy(self):
        return _nlp.SwigPyIterator_copy(self)

    def next(self):
        return _nlp.SwigPyIterator_next(self)

    def __next__(self):
        return _nlp.SwigPyIterator___next__(self)

    def previous(self):
        return _nlp.SwigPyIterator_previous(self)

    def advance(self, n):
        return _nlp.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _nlp.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _nlp.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _nlp.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _nlp.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _nlp.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _nlp.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _nlp.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vectori(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectori, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectori, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _nlp.vectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _nlp.vectori___nonzero__(self)

    def __bool__(self):
        return _nlp.vectori___bool__(self)

    def __len__(self):
        return _nlp.vectori___len__(self)

    def pop(self):
        return _nlp.vectori_pop(self)

    def __getslice__(self, i, j):
        return _nlp.vectori___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _nlp.vectori___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _nlp.vectori___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _nlp.vectori___delitem__(self, *args)

    def __getitem__(self, *args):
        return _nlp.vectori___getitem__(self, *args)

    def __setitem__(self, *args):
        return _nlp.vectori___setitem__(self, *args)

    def append(self, x):
        return _nlp.vectori_append(self, x)

    def empty(self):
        return _nlp.vectori_empty(self)

    def size(self):
        return _nlp.vectori_size(self)

    def clear(self):
        return _nlp.vectori_clear(self)

    def swap(self, v):
        return _nlp.vectori_swap(self, v)

    def get_allocator(self):
        return _nlp.vectori_get_allocator(self)

    def begin(self):
        return _nlp.vectori_begin(self)

    def end(self):
        return _nlp.vectori_end(self)

    def rbegin(self):
        return _nlp.vectori_rbegin(self)

    def rend(self):
        return _nlp.vectori_rend(self)

    def pop_back(self):
        return _nlp.vectori_pop_back(self)

    def erase(self, *args):
        return _nlp.vectori_erase(self, *args)

    def __init__(self, *args):
        this = _nlp.new_vectori(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _nlp.vectori_push_back(self, x)

    def front(self):
        return _nlp.vectori_front(self)

    def back(self):
        return _nlp.vectori_back(self)

    def assign(self, n, x):
        return _nlp.vectori_assign(self, n, x)

    def resize(self, *args):
        return _nlp.vectori_resize(self, *args)

    def insert(self, *args):
        return _nlp.vectori_insert(self, *args)

    def reserve(self, n):
        return _nlp.vectori_reserve(self, n)

    def capacity(self):
        return _nlp.vectori_capacity(self)
    __swig_destroy__ = _nlp.delete_vectori
    __del__ = lambda self: None
vectori_swigregister = _nlp.vectori_swigregister
vectori_swigregister(vectori)

class vectord(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectord, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectord, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _nlp.vectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _nlp.vectord___nonzero__(self)

    def __bool__(self):
        return _nlp.vectord___bool__(self)

    def __len__(self):
        return _nlp.vectord___len__(self)

    def pop(self):
        return _nlp.vectord_pop(self)

    def __getslice__(self, i, j):
        return _nlp.vectord___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _nlp.vectord___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _nlp.vectord___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _nlp.vectord___delitem__(self, *args)

    def __getitem__(self, *args):
        return _nlp.vectord___getitem__(self, *args)

    def __setitem__(self, *args):
        return _nlp.vectord___setitem__(self, *args)

    def append(self, x):
        return _nlp.vectord_append(self, x)

    def empty(self):
        return _nlp.vectord_empty(self)

    def size(self):
        return _nlp.vectord_size(self)

    def clear(self):
        return _nlp.vectord_clear(self)

    def swap(self, v):
        return _nlp.vectord_swap(self, v)

    def get_allocator(self):
        return _nlp.vectord_get_allocator(self)

    def begin(self):
        return _nlp.vectord_begin(self)

    def end(self):
        return _nlp.vectord_end(self)

    def rbegin(self):
        return _nlp.vectord_rbegin(self)

    def rend(self):
        return _nlp.vectord_rend(self)

    def pop_back(self):
        return _nlp.vectord_pop_back(self)

    def erase(self, *args):
        return _nlp.vectord_erase(self, *args)

    def __init__(self, *args):
        this = _nlp.new_vectord(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _nlp.vectord_push_back(self, x)

    def front(self):
        return _nlp.vectord_front(self)

    def back(self):
        return _nlp.vectord_back(self)

    def assign(self, n, x):
        return _nlp.vectord_assign(self, n, x)

    def resize(self, *args):
        return _nlp.vectord_resize(self, *args)

    def insert(self, *args):
        return _nlp.vectord_insert(self, *args)

    def reserve(self, n):
        return _nlp.vectord_reserve(self, n)

    def capacity(self):
        return _nlp.vectord_capacity(self)
    __swig_destroy__ = _nlp.delete_vectord
    __del__ = lambda self: None
vectord_swigregister = _nlp.vectord_swigregister
vectord_swigregister(vectord)

class charp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, charp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, charp, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _nlp.new_charp()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _nlp.delete_charp
    __del__ = lambda self: None

    def assign(self, value):
        return _nlp.charp_assign(self, value)

    def value(self):
        return _nlp.charp_value(self)

    def cast(self):
        return _nlp.charp_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _nlp.charp_frompointer
    if _newclass:
        frompointer = staticmethod(_nlp.charp_frompointer)
charp_swigregister = _nlp.charp_swigregister
charp_swigregister(charp)

def charp_frompointer(t):
    return _nlp.charp_frompointer(t)
charp_frompointer = _nlp.charp_frompointer

class Term(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Term, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Term, name)
    __repr__ = _swig_repr
    __swig_setmethods__["letters"] = _nlp.Term_letters_set
    __swig_getmethods__["letters"] = _nlp.Term_letters_get
    if _newclass:
        letters = _swig_property(_nlp.Term_letters_get, _nlp.Term_letters_set)

    def __init__(self):
        this = _nlp.new_Term()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _nlp.delete_Term
    __del__ = lambda self: None
Term_swigregister = _nlp.Term_swigregister
Term_swigregister(Term)

class Vocab(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Vocab, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Vocab, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _nlp.new_Vocab()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_setmethods__["size"] = _nlp.Vocab_size_set
    __swig_getmethods__["size"] = _nlp.Vocab_size_get
    if _newclass:
        size = _swig_property(_nlp.Vocab_size_get, _nlp.Vocab_size_set)
    __swig_setmethods__["vocab_buffer_size"] = _nlp.Vocab_vocab_buffer_size_set
    __swig_getmethods__["vocab_buffer_size"] = _nlp.Vocab_vocab_buffer_size_get
    if _newclass:
        vocab_buffer_size = _swig_property(_nlp.Vocab_vocab_buffer_size_get, _nlp.Vocab_vocab_buffer_size_set)
    __swig_setmethods__["vocab"] = _nlp.Vocab_vocab_set
    __swig_getmethods__["vocab"] = _nlp.Vocab_vocab_get
    if _newclass:
        vocab = _swig_property(_nlp.Vocab_vocab_get, _nlp.Vocab_vocab_set)
    __swig_setmethods__["hash_size"] = _nlp.Vocab_hash_size_set
    __swig_getmethods__["hash_size"] = _nlp.Vocab_hash_size_get
    if _newclass:
        hash_size = _swig_property(_nlp.Vocab_hash_size_get, _nlp.Vocab_hash_size_set)
    __swig_setmethods__["hash_table"] = _nlp.Vocab_hash_table_set
    __swig_getmethods__["hash_table"] = _nlp.Vocab_hash_table_get
    if _newclass:
        hash_table = _swig_property(_nlp.Vocab_hash_table_get, _nlp.Vocab_hash_table_set)

    def addTerm(self, term):
        return _nlp.Vocab_addTerm(self, term)

    def getTermHash(self, term):
        return _nlp.Vocab_getTermHash(self, term)

    def getTermAtIndex(self, i):
        return _nlp.Vocab_getTermAtIndex(self, i)

    def getTermIndex(self, term):
        return _nlp.Vocab_getTermIndex(self, term)
    __swig_destroy__ = _nlp.delete_Vocab
    __del__ = lambda self: None
Vocab_swigregister = _nlp.Vocab_swigregister
Vocab_swigregister(Vocab)

class Text(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Text, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Text, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sequences"] = _nlp.Text_sequences_set
    __swig_getmethods__["sequences"] = _nlp.Text_sequences_get
    if _newclass:
        sequences = _swig_property(_nlp.Text_sequences_get, _nlp.Text_sequences_set)
    __swig_setmethods__["sequence_BIOs"] = _nlp.Text_sequence_BIOs_set
    __swig_getmethods__["sequence_BIOs"] = _nlp.Text_sequence_BIOs_get
    if _newclass:
        sequence_BIOs = _swig_property(_nlp.Text_sequence_BIOs_get, _nlp.Text_sequence_BIOs_set)
    __swig_setmethods__["sequence_vocabs"] = _nlp.Text_sequence_vocabs_set
    __swig_getmethods__["sequence_vocabs"] = _nlp.Text_sequence_vocabs_get
    if _newclass:
        sequence_vocabs = _swig_property(_nlp.Text_sequence_vocabs_get, _nlp.Text_sequence_vocabs_set)

    def __init__(self, *args):
        this = _nlp.new_Text(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def createVocabForNewSequence(self, key):
        return _nlp.Text_createVocabForNewSequence(self, key)

    def addSequence(self, key, sequence, vocab):
        return _nlp.Text_addSequence(self, key, sequence, vocab)

    def segmentSequenceIntoNewSequence(self, raw_key, bio, seg_key, seg_vocab):
        return _nlp.Text_segmentSequenceIntoNewSequence(self, raw_key, bio, seg_key, seg_vocab)

    def getVocab(self, key):
        return _nlp.Text_getVocab(self, key)

    def getSequence(self, key):
        return _nlp.Text_getSequence(self, key)
    __swig_destroy__ = _nlp.delete_Text
    __del__ = lambda self: None
Text_swigregister = _nlp.Text_swigregister
Text_swigregister(Text)

# This file is compatible with both classic and new-style classes.


