/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: linguamind/nn.i

package nn

import "unsafe"
import _ "runtime/cgo"
import "sync"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

var _wrap_Swig_free_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_Swig_free(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Swig_free_nn_adbe78f3a6a66401, _swig_p)
	return
}

func Swig_free(arg1 uintptr) {
	_swig_wrap_Swig_free(arg1)
}

var _wrap_Swig_malloc_nn_adbe78f3a6a66401 unsafe.Pointer

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_Swig_malloc_nn_adbe78f3a6a66401, _swig_p)
	return
}
type SwigcptrVectori uintptr

func (p SwigcptrVectori) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVectori) SwigIsVectori() {
}

var _wrap_new_vectori__SWIG_0_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_new_vectori__SWIG_0() (base SwigcptrVectori) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_vectori__SWIG_0_nn_adbe78f3a6a66401, _swig_p)
	return
}

func NewVectori__SWIG_0() (_swig_ret Vectori) {
	return _swig_wrap_new_vectori__SWIG_0()
}

var _wrap_new_vectori__SWIG_1_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_new_vectori__SWIG_1(base int64) (_ SwigcptrVectori) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_vectori__SWIG_1_nn_adbe78f3a6a66401, _swig_p)
	return
}

func NewVectori__SWIG_1(arg1 int64) (_swig_ret Vectori) {
	return _swig_wrap_new_vectori__SWIG_1(arg1)
}

func NewVectori(a ...interface{}) Vectori {
	argc := len(a)
	if argc == 0 {
		return NewVectori__SWIG_0()
	}
	if argc == 1 {
		return NewVectori__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

var _wrap_vectori_size_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectori_size(base SwigcptrVectori) (_ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_size_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Size() (_swig_ret int64) {
	return _swig_wrap_vectori_size(arg1)
}

var _wrap_vectori_capacity_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectori_capacity(base SwigcptrVectori) (_ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_capacity_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Capacity() (_swig_ret int64) {
	return _swig_wrap_vectori_capacity(arg1)
}

var _wrap_vectori_reserve_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectori_reserve(base SwigcptrVectori, _ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_reserve_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Reserve(arg2 int64) {
	_swig_wrap_vectori_reserve(arg1, arg2)
}

var _wrap_vectori_isEmpty_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectori_isEmpty(base SwigcptrVectori) (_ bool) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_isEmpty_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectori) IsEmpty() (_swig_ret bool) {
	return _swig_wrap_vectori_isEmpty(arg1)
}

var _wrap_vectori_clear_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectori_clear(base SwigcptrVectori) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_clear_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Clear() {
	_swig_wrap_vectori_clear(arg1)
}

var _wrap_vectori_add_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectori_add(base SwigcptrVectori, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_add_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Add(arg2 int) {
	_swig_wrap_vectori_add(arg1, arg2)
}

var _wrap_vectori_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectori_get(base SwigcptrVectori, _ int) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Get(arg2 int) (_swig_ret int) {
	return _swig_wrap_vectori_get(arg1, arg2)
}

var _wrap_vectori_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectori_set(base SwigcptrVectori, _ int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectori_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectori) Set(arg2 int, arg3 int) {
	_swig_wrap_vectori_set(arg1, arg2, arg3)
}

var _wrap_delete_vectori_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_delete_vectori(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_vectori_nn_adbe78f3a6a66401, _swig_p)
	return
}

func DeleteVectori(arg1 Vectori) {
	_swig_wrap_delete_vectori(arg1.Swigcptr())
}

type Vectori interface {
	Swigcptr() uintptr
	SwigIsVectori()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 int)
	Get(arg2 int) (_swig_ret int)
	Set(arg2 int, arg3 int)
}

type SwigcptrVectord uintptr

func (p SwigcptrVectord) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVectord) SwigIsVectord() {
}

var _wrap_new_vectord__SWIG_0_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_new_vectord__SWIG_0() (base SwigcptrVectord) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_vectord__SWIG_0_nn_adbe78f3a6a66401, _swig_p)
	return
}

func NewVectord__SWIG_0() (_swig_ret Vectord) {
	return _swig_wrap_new_vectord__SWIG_0()
}

var _wrap_new_vectord__SWIG_1_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_new_vectord__SWIG_1(base int64) (_ SwigcptrVectord) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_vectord__SWIG_1_nn_adbe78f3a6a66401, _swig_p)
	return
}

func NewVectord__SWIG_1(arg1 int64) (_swig_ret Vectord) {
	return _swig_wrap_new_vectord__SWIG_1(arg1)
}

func NewVectord(a ...interface{}) Vectord {
	argc := len(a)
	if argc == 0 {
		return NewVectord__SWIG_0()
	}
	if argc == 1 {
		return NewVectord__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

var _wrap_vectord_size_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectord_size(base SwigcptrVectord) (_ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_size_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Size() (_swig_ret int64) {
	return _swig_wrap_vectord_size(arg1)
}

var _wrap_vectord_capacity_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectord_capacity(base SwigcptrVectord) (_ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_capacity_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Capacity() (_swig_ret int64) {
	return _swig_wrap_vectord_capacity(arg1)
}

var _wrap_vectord_reserve_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectord_reserve(base SwigcptrVectord, _ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_reserve_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Reserve(arg2 int64) {
	_swig_wrap_vectord_reserve(arg1, arg2)
}

var _wrap_vectord_isEmpty_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectord_isEmpty(base SwigcptrVectord) (_ bool) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_isEmpty_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectord) IsEmpty() (_swig_ret bool) {
	return _swig_wrap_vectord_isEmpty(arg1)
}

var _wrap_vectord_clear_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectord_clear(base SwigcptrVectord) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_clear_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Clear() {
	_swig_wrap_vectord_clear(arg1)
}

var _wrap_vectord_add_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectord_add(base SwigcptrVectord, _ float64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_add_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Add(arg2 float64) {
	_swig_wrap_vectord_add(arg1, arg2)
}

var _wrap_vectord_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectord_get(base SwigcptrVectord, _ int) (_ float64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Get(arg2 int) (_swig_ret float64) {
	return _swig_wrap_vectord_get(arg1, arg2)
}

var _wrap_vectord_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_vectord_set(base SwigcptrVectord, _ int, _ float64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_vectord_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrVectord) Set(arg2 int, arg3 float64) {
	_swig_wrap_vectord_set(arg1, arg2, arg3)
}

var _wrap_delete_vectord_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_delete_vectord(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_vectord_nn_adbe78f3a6a66401, _swig_p)
	return
}

func DeleteVectord(arg1 Vectord) {
	_swig_wrap_delete_vectord(arg1.Swigcptr())
}

type Vectord interface {
	Swigcptr() uintptr
	SwigIsVectord()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 float64)
	Get(arg2 int) (_swig_ret float64)
	Set(arg2 int, arg3 float64)
}

type SwigcptrCharp uintptr

func (p SwigcptrCharp) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCharp) SwigIsCharp() {
}

var _wrap_new_charp_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_new_charp() (base SwigcptrCharp) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_charp_nn_adbe78f3a6a66401, _swig_p)
	return
}

func NewCharp() (_swig_ret Charp) {
	return _swig_wrap_new_charp()
}

var _wrap_delete_charp_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_delete_charp(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_charp_nn_adbe78f3a6a66401, _swig_p)
	return
}

func DeleteCharp(arg1 Charp) {
	_swig_wrap_delete_charp(arg1.Swigcptr())
}

var _wrap_charp_assign_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_charp_assign(base SwigcptrCharp, _ byte) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_charp_assign_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrCharp) Assign(arg2 byte) {
	_swig_wrap_charp_assign(arg1, arg2)
}

var _wrap_charp_value_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_charp_value(base SwigcptrCharp) (_ byte) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_charp_value_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrCharp) Value() (_swig_ret byte) {
	return _swig_wrap_charp_value(arg1)
}

var _wrap_charp_cast_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_charp_cast(base SwigcptrCharp) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_charp_cast_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrCharp) Cast() (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_charp_cast(arg1)
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_charp_frompointer_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_charp_frompointer(base string) (_ SwigcptrCharp) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_charp_frompointer_nn_adbe78f3a6a66401, _swig_p)
	return
}

func CharpFrompointer(arg1 string) (_swig_ret Charp) {
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return _swig_wrap_charp_frompointer(arg1)
}

type Charp interface {
	Swigcptr() uintptr
	SwigIsCharp()
	Assign(arg2 byte)
	Value() (_swig_ret byte)
	Cast() (_swig_ret string)
}

type SwigcptrLayer uintptr

func (p SwigcptrLayer) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrLayer) SwigIsLayer() {
}

var _wrap_new_Layer_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_new_Layer() (base SwigcptrLayer) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Layer_nn_adbe78f3a6a66401, _swig_p)
	return
}

func NewLayer() (_swig_ret Layer) {
	return _swig_wrap_new_Layer()
}

var _wrap_Layer_weights_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_Layer_weights_set(base SwigcptrLayer, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Layer_weights_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrLayer) SetWeights(arg2 Tensor) {
	_swig_wrap_Layer_weights_set(arg1, arg2.Swigcptr())
}

var _wrap_Layer_weights_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_Layer_weights_get(base SwigcptrLayer) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Layer_weights_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrLayer) GetWeights() (_swig_ret Tensor) {
	return _swig_wrap_Layer_weights_get(arg1)
}

var _wrap_Layer_output_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_Layer_output_set(base SwigcptrLayer, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Layer_output_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrLayer) SetOutput(arg2 Tensor) {
	_swig_wrap_Layer_output_set(arg1, arg2.Swigcptr())
}

var _wrap_Layer_output_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_Layer_output_get(base SwigcptrLayer) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Layer_output_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrLayer) GetOutput() (_swig_ret Tensor) {
	return _swig_wrap_Layer_output_get(arg1)
}

var _wrap_delete_Layer_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_delete_Layer(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Layer_nn_adbe78f3a6a66401, _swig_p)
	return
}

func DeleteLayer(arg1 Layer) {
	_swig_wrap_delete_Layer(arg1.Swigcptr())
}

type Layer interface {
	Swigcptr() uintptr
	SwigIsLayer()
	SetWeights(arg2 Tensor)
	GetWeights() (_swig_ret Tensor)
	SetOutput(arg2 Tensor)
	GetOutput() (_swig_ret Tensor)
}

type SwigcptrSparseLinearInput uintptr

func (p SwigcptrSparseLinearInput) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSparseLinearInput) SwigIsSparseLinearInput() {
}

var _wrap_new_SparseLinearInput_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_new_SparseLinearInput(base int, _ int) (_ SwigcptrSparseLinearInput) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_SparseLinearInput_nn_adbe78f3a6a66401, _swig_p)
	return
}

func NewSparseLinearInput(arg1 int, arg2 int) (_swig_ret SparseLinearInput) {
	return _swig_wrap_new_SparseLinearInput(arg1, arg2)
}

var _wrap_SparseLinearInput_weights_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearInput_weights_set(base SwigcptrSparseLinearInput, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearInput_weights_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearInput) SetWeights(arg2 Tensor) {
	_swig_wrap_SparseLinearInput_weights_set(arg1, arg2.Swigcptr())
}

var _wrap_SparseLinearInput_weights_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearInput_weights_get(base SwigcptrSparseLinearInput) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearInput_weights_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearInput) GetWeights() (_swig_ret Tensor) {
	return _swig_wrap_SparseLinearInput_weights_get(arg1)
}

var _wrap_SparseLinearInput_output_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearInput_output_set(base SwigcptrSparseLinearInput, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearInput_output_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearInput) SetOutput(arg2 Tensor) {
	_swig_wrap_SparseLinearInput_output_set(arg1, arg2.Swigcptr())
}

var _wrap_SparseLinearInput_output_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearInput_output_get(base SwigcptrSparseLinearInput) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearInput_output_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearInput) GetOutput() (_swig_ret Tensor) {
	return _swig_wrap_SparseLinearInput_output_get(arg1)
}

var _wrap_SparseLinearInput_init_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearInput_init(base SwigcptrSparseLinearInput, _ int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearInput_init_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearInput) Init(arg2 int, arg3 int) {
	_swig_wrap_SparseLinearInput_init(arg1, arg2, arg3)
}

var _wrap_SparseLinearInput_updateOutput_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearInput_updateOutput(base SwigcptrSparseLinearInput, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearInput_updateOutput_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearInput) UpdateOutput(arg2 Vectori) {
	_swig_wrap_SparseLinearInput_updateOutput(arg1, arg2.Swigcptr())
}

var _wrap_delete_SparseLinearInput_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_delete_SparseLinearInput(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_SparseLinearInput_nn_adbe78f3a6a66401, _swig_p)
	return
}

func DeleteSparseLinearInput(arg1 SparseLinearInput) {
	_swig_wrap_delete_SparseLinearInput(arg1.Swigcptr())
}

func (p SwigcptrSparseLinearInput) SwigIsLayer() {
}

func (p SwigcptrSparseLinearInput) SwigGetLayer() Layer {
	return SwigcptrLayer(p.Swigcptr())
}

type SparseLinearInput interface {
	Swigcptr() uintptr
	SwigIsSparseLinearInput()
	SetWeights(arg2 Tensor)
	GetWeights() (_swig_ret Tensor)
	SetOutput(arg2 Tensor)
	GetOutput() (_swig_ret Tensor)
	Init(arg2 int, arg3 int)
	UpdateOutput(arg2 Vectori)
	SwigIsLayer()
	SwigGetLayer() Layer
}

type SwigcptrSparseLinearOutput uintptr

func (p SwigcptrSparseLinearOutput) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSparseLinearOutput) SwigIsSparseLinearOutput() {
}

var _wrap_new_SparseLinearOutput_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_new_SparseLinearOutput(base int, _ int, _ int) (_ SwigcptrSparseLinearOutput) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_SparseLinearOutput_nn_adbe78f3a6a66401, _swig_p)
	return
}

func NewSparseLinearOutput(arg1 int, arg2 int, arg3 int) (_swig_ret SparseLinearOutput) {
	return _swig_wrap_new_SparseLinearOutput(arg1, arg2, arg3)
}

var _wrap_SparseLinearOutput_weights_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearOutput_weights_set(base SwigcptrSparseLinearOutput, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearOutput_weights_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearOutput) SetWeights(arg2 Tensor) {
	_swig_wrap_SparseLinearOutput_weights_set(arg1, arg2.Swigcptr())
}

var _wrap_SparseLinearOutput_weights_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearOutput_weights_get(base SwigcptrSparseLinearOutput) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearOutput_weights_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearOutput) GetWeights() (_swig_ret Tensor) {
	return _swig_wrap_SparseLinearOutput_weights_get(arg1)
}

var _wrap_SparseLinearOutput_output_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearOutput_output_set(base SwigcptrSparseLinearOutput, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearOutput_output_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearOutput) SetOutput(arg2 Tensor) {
	_swig_wrap_SparseLinearOutput_output_set(arg1, arg2.Swigcptr())
}

var _wrap_SparseLinearOutput_output_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearOutput_output_get(base SwigcptrSparseLinearOutput) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearOutput_output_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearOutput) GetOutput() (_swig_ret Tensor) {
	return _swig_wrap_SparseLinearOutput_output_get(arg1)
}

var _wrap_SparseLinearOutput_output_indices_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearOutput_output_indices_set(base SwigcptrSparseLinearOutput, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearOutput_output_indices_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearOutput) SetOutput_indices(arg2 Vectori) {
	_swig_wrap_SparseLinearOutput_output_indices_set(arg1, arg2.Swigcptr())
}

var _wrap_SparseLinearOutput_output_indices_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearOutput_output_indices_get(base SwigcptrSparseLinearOutput) (_ SwigcptrVectori) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearOutput_output_indices_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearOutput) GetOutput_indices() (_swig_ret Vectori) {
	return _swig_wrap_SparseLinearOutput_output_indices_get(arg1)
}

var _wrap_SparseLinearOutput_init_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearOutput_init(base SwigcptrSparseLinearOutput, _ int, _ int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearOutput_init_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearOutput) Init(arg2 int, arg3 int, arg4 int) {
	_swig_wrap_SparseLinearOutput_init(arg1, arg2, arg3, arg4)
}

var _wrap_SparseLinearOutput_updateOutput_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_SparseLinearOutput_updateOutput(base SwigcptrSparseLinearOutput, _ uintptr, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SparseLinearOutput_updateOutput_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSparseLinearOutput) UpdateOutput(arg2 Tensor, arg3 Vectori) {
	_swig_wrap_SparseLinearOutput_updateOutput(arg1, arg2.Swigcptr(), arg3.Swigcptr())
}

var _wrap_delete_SparseLinearOutput_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_delete_SparseLinearOutput(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_SparseLinearOutput_nn_adbe78f3a6a66401, _swig_p)
	return
}

func DeleteSparseLinearOutput(arg1 SparseLinearOutput) {
	_swig_wrap_delete_SparseLinearOutput(arg1.Swigcptr())
}

func (p SwigcptrSparseLinearOutput) SwigIsLayer() {
}

func (p SwigcptrSparseLinearOutput) SwigGetLayer() Layer {
	return SwigcptrLayer(p.Swigcptr())
}

type SparseLinearOutput interface {
	Swigcptr() uintptr
	SwigIsSparseLinearOutput()
	SetWeights(arg2 Tensor)
	GetWeights() (_swig_ret Tensor)
	SetOutput(arg2 Tensor)
	GetOutput() (_swig_ret Tensor)
	SetOutput_indices(arg2 Vectori)
	GetOutput_indices() (_swig_ret Vectori)
	Init(arg2 int, arg3 int, arg4 int)
	UpdateOutput(arg2 Tensor, arg3 Vectori)
	SwigIsLayer()
	SwigGetLayer() Layer
}

type SwigcptrSequential uintptr

func (p SwigcptrSequential) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSequential) SwigIsSequential() {
}

var _wrap_new_Sequential_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_new_Sequential() (base SwigcptrSequential) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Sequential_nn_adbe78f3a6a66401, _swig_p)
	return
}

func NewSequential() (_swig_ret Sequential) {
	return _swig_wrap_new_Sequential()
}

var _wrap_Sequential_layers_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_Sequential_layers_set(base SwigcptrSequential, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Sequential_layers_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSequential) SetLayers(arg2 Std_vector_Sl_Layer_Sm__Sg_) {
	_swig_wrap_Sequential_layers_set(arg1, arg2.Swigcptr())
}

var _wrap_Sequential_layers_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_Sequential_layers_get(base SwigcptrSequential) (_ SwigcptrStd_vector_Sl_Layer_Sm__Sg_) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Sequential_layers_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSequential) GetLayers() (_swig_ret Std_vector_Sl_Layer_Sm__Sg_) {
	return _swig_wrap_Sequential_layers_get(arg1)
}

var _wrap_Sequential_output_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_Sequential_output_set(base SwigcptrSequential, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Sequential_output_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSequential) SetOutput(arg2 Tensor) {
	_swig_wrap_Sequential_output_set(arg1, arg2.Swigcptr())
}

var _wrap_Sequential_output_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_Sequential_output_get(base SwigcptrSequential) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Sequential_output_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSequential) GetOutput() (_swig_ret Tensor) {
	return _swig_wrap_Sequential_output_get(arg1)
}

var _wrap_Sequential_add_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_Sequential_add(base SwigcptrSequential, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Sequential_add_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSequential) Add(arg2 Layer) {
	_swig_wrap_Sequential_add(arg1, arg2.Swigcptr())
}

var _wrap_Sequential_forward_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_Sequential_forward(base SwigcptrSequential, _ uintptr, _ uintptr) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Sequential_forward_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrSequential) Forward(arg2 Vectori, arg3 Vectori) (_swig_ret Tensor) {
	return _swig_wrap_Sequential_forward(arg1, arg2.Swigcptr(), arg3.Swigcptr())
}

var _wrap_delete_Sequential_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_delete_Sequential(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Sequential_nn_adbe78f3a6a66401, _swig_p)
	return
}

func DeleteSequential(arg1 Sequential) {
	_swig_wrap_delete_Sequential(arg1.Swigcptr())
}

type Sequential interface {
	Swigcptr() uintptr
	SwigIsSequential()
	SetLayers(arg2 Std_vector_Sl_Layer_Sm__Sg_)
	GetLayers() (_swig_ret Std_vector_Sl_Layer_Sm__Sg_)
	SetOutput(arg2 Tensor)
	GetOutput() (_swig_ret Tensor)
	Add(arg2 Layer)
	Forward(arg2 Vectori, arg3 Vectori) (_swig_ret Tensor)
}

type SwigcptrMSECriterion uintptr

func (p SwigcptrMSECriterion) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrMSECriterion) SwigIsMSECriterion() {
}

var _wrap_MSECriterion_batch_size_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_MSECriterion_batch_size_set(base SwigcptrMSECriterion, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_MSECriterion_batch_size_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrMSECriterion) SetBatch_size(arg2 int) {
	_swig_wrap_MSECriterion_batch_size_set(arg1, arg2)
}

var _wrap_MSECriterion_batch_size_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_MSECriterion_batch_size_get(base SwigcptrMSECriterion) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_MSECriterion_batch_size_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrMSECriterion) GetBatch_size() (_swig_ret int) {
	return _swig_wrap_MSECriterion_batch_size_get(arg1)
}

var _wrap_MSECriterion_dim_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_MSECriterion_dim_set(base SwigcptrMSECriterion, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_MSECriterion_dim_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrMSECriterion) SetDim(arg2 int) {
	_swig_wrap_MSECriterion_dim_set(arg1, arg2)
}

var _wrap_MSECriterion_dim_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_MSECriterion_dim_get(base SwigcptrMSECriterion) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_MSECriterion_dim_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrMSECriterion) GetDim() (_swig_ret int) {
	return _swig_wrap_MSECriterion_dim_get(arg1)
}

var _wrap_MSECriterion_output_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_MSECriterion_output_set(base SwigcptrMSECriterion, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_MSECriterion_output_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrMSECriterion) SetOutput(arg2 Tensor) {
	_swig_wrap_MSECriterion_output_set(arg1, arg2.Swigcptr())
}

var _wrap_MSECriterion_output_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_MSECriterion_output_get(base SwigcptrMSECriterion) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_MSECriterion_output_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrMSECriterion) GetOutput() (_swig_ret Tensor) {
	return _swig_wrap_MSECriterion_output_get(arg1)
}

var _wrap_MSECriterion_grad_input_set_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_MSECriterion_grad_input_set(base SwigcptrMSECriterion, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_MSECriterion_grad_input_set_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrMSECriterion) SetGrad_input(arg2 Tensor) {
	_swig_wrap_MSECriterion_grad_input_set(arg1, arg2.Swigcptr())
}

var _wrap_MSECriterion_grad_input_get_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_MSECriterion_grad_input_get(base SwigcptrMSECriterion) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_MSECriterion_grad_input_get_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrMSECriterion) GetGrad_input() (_swig_ret Tensor) {
	return _swig_wrap_MSECriterion_grad_input_get(arg1)
}

var _wrap_new_MSECriterion_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_new_MSECriterion(base int, _ int) (_ SwigcptrMSECriterion) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_MSECriterion_nn_adbe78f3a6a66401, _swig_p)
	return
}

func NewMSECriterion(arg1 int, arg2 int) (_swig_ret MSECriterion) {
	return _swig_wrap_new_MSECriterion(arg1, arg2)
}

var _wrap_MSECriterion_forwards_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_MSECriterion_forwards(base SwigcptrMSECriterion, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_MSECriterion_forwards_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrMSECriterion) Forwards(arg2 Tensor) {
	_swig_wrap_MSECriterion_forwards(arg1, arg2.Swigcptr())
}

var _wrap_MSECriterion_backwards_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_MSECriterion_backwards(base SwigcptrMSECriterion, _ uintptr) (_ SwigcptrTensor) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_MSECriterion_backwards_nn_adbe78f3a6a66401, _swig_p)
	return
}

func (arg1 SwigcptrMSECriterion) Backwards(arg2 Tensor) (_swig_ret Tensor) {
	return _swig_wrap_MSECriterion_backwards(arg1, arg2.Swigcptr())
}

var _wrap_delete_MSECriterion_nn_adbe78f3a6a66401 unsafe.Pointer

func _swig_wrap_delete_MSECriterion(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_MSECriterion_nn_adbe78f3a6a66401, _swig_p)
	return
}

func DeleteMSECriterion(arg1 MSECriterion) {
	_swig_wrap_delete_MSECriterion(arg1.Swigcptr())
}

type MSECriterion interface {
	Swigcptr() uintptr
	SwigIsMSECriterion()
	SetBatch_size(arg2 int)
	GetBatch_size() (_swig_ret int)
	SetDim(arg2 int)
	GetDim() (_swig_ret int)
	SetOutput(arg2 Tensor)
	GetOutput() (_swig_ret Tensor)
	SetGrad_input(arg2 Tensor)
	GetGrad_input() (_swig_ret Tensor)
	Forwards(arg2 Tensor)
	Backwards(arg2 Tensor) (_swig_ret Tensor)
}


type SwigcptrTensor uintptr
type Tensor interface {
	Swigcptr() uintptr;
}
func (p SwigcptrTensor) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_Layer_Sm__Sg_ uintptr
type Std_vector_Sl_Layer_Sm__Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_Layer_Sm__Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

