# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_nn', [dirname(__file__)])
        except ImportError:
            import _nn
            return _nn
        if fp is not None:
            try:
                _mod = imp.load_module('_nn', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _nn = swig_import_helper()
    del swig_import_helper
else:
    import _nn
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _nn.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _nn.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _nn.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _nn.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _nn.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _nn.SwigPyIterator_equal(self, x)

    def copy(self):
        return _nn.SwigPyIterator_copy(self)

    def next(self):
        return _nn.SwigPyIterator_next(self)

    def __next__(self):
        return _nn.SwigPyIterator___next__(self)

    def previous(self):
        return _nn.SwigPyIterator_previous(self)

    def advance(self, n):
        return _nn.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _nn.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _nn.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _nn.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _nn.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _nn.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _nn.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _nn.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vectori(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectori, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectori, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _nn.vectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _nn.vectori___nonzero__(self)

    def __bool__(self):
        return _nn.vectori___bool__(self)

    def __len__(self):
        return _nn.vectori___len__(self)

    def pop(self):
        return _nn.vectori_pop(self)

    def __getslice__(self, i, j):
        return _nn.vectori___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _nn.vectori___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _nn.vectori___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _nn.vectori___delitem__(self, *args)

    def __getitem__(self, *args):
        return _nn.vectori___getitem__(self, *args)

    def __setitem__(self, *args):
        return _nn.vectori___setitem__(self, *args)

    def append(self, x):
        return _nn.vectori_append(self, x)

    def empty(self):
        return _nn.vectori_empty(self)

    def size(self):
        return _nn.vectori_size(self)

    def clear(self):
        return _nn.vectori_clear(self)

    def swap(self, v):
        return _nn.vectori_swap(self, v)

    def get_allocator(self):
        return _nn.vectori_get_allocator(self)

    def begin(self):
        return _nn.vectori_begin(self)

    def end(self):
        return _nn.vectori_end(self)

    def rbegin(self):
        return _nn.vectori_rbegin(self)

    def rend(self):
        return _nn.vectori_rend(self)

    def pop_back(self):
        return _nn.vectori_pop_back(self)

    def erase(self, *args):
        return _nn.vectori_erase(self, *args)

    def __init__(self, *args):
        this = _nn.new_vectori(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _nn.vectori_push_back(self, x)

    def front(self):
        return _nn.vectori_front(self)

    def back(self):
        return _nn.vectori_back(self)

    def assign(self, n, x):
        return _nn.vectori_assign(self, n, x)

    def resize(self, *args):
        return _nn.vectori_resize(self, *args)

    def insert(self, *args):
        return _nn.vectori_insert(self, *args)

    def reserve(self, n):
        return _nn.vectori_reserve(self, n)

    def capacity(self):
        return _nn.vectori_capacity(self)
    __swig_destroy__ = _nn.delete_vectori
    __del__ = lambda self: None
vectori_swigregister = _nn.vectori_swigregister
vectori_swigregister(vectori)

class vectord(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectord, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectord, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _nn.vectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _nn.vectord___nonzero__(self)

    def __bool__(self):
        return _nn.vectord___bool__(self)

    def __len__(self):
        return _nn.vectord___len__(self)

    def pop(self):
        return _nn.vectord_pop(self)

    def __getslice__(self, i, j):
        return _nn.vectord___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _nn.vectord___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _nn.vectord___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _nn.vectord___delitem__(self, *args)

    def __getitem__(self, *args):
        return _nn.vectord___getitem__(self, *args)

    def __setitem__(self, *args):
        return _nn.vectord___setitem__(self, *args)

    def append(self, x):
        return _nn.vectord_append(self, x)

    def empty(self):
        return _nn.vectord_empty(self)

    def size(self):
        return _nn.vectord_size(self)

    def clear(self):
        return _nn.vectord_clear(self)

    def swap(self, v):
        return _nn.vectord_swap(self, v)

    def get_allocator(self):
        return _nn.vectord_get_allocator(self)

    def begin(self):
        return _nn.vectord_begin(self)

    def end(self):
        return _nn.vectord_end(self)

    def rbegin(self):
        return _nn.vectord_rbegin(self)

    def rend(self):
        return _nn.vectord_rend(self)

    def pop_back(self):
        return _nn.vectord_pop_back(self)

    def erase(self, *args):
        return _nn.vectord_erase(self, *args)

    def __init__(self, *args):
        this = _nn.new_vectord(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _nn.vectord_push_back(self, x)

    def front(self):
        return _nn.vectord_front(self)

    def back(self):
        return _nn.vectord_back(self)

    def assign(self, n, x):
        return _nn.vectord_assign(self, n, x)

    def resize(self, *args):
        return _nn.vectord_resize(self, *args)

    def insert(self, *args):
        return _nn.vectord_insert(self, *args)

    def reserve(self, n):
        return _nn.vectord_reserve(self, n)

    def capacity(self):
        return _nn.vectord_capacity(self)
    __swig_destroy__ = _nn.delete_vectord
    __del__ = lambda self: None
vectord_swigregister = _nn.vectord_swigregister
vectord_swigregister(vectord)

class charp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, charp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, charp, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _nn.new_charp()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _nn.delete_charp
    __del__ = lambda self: None

    def assign(self, value):
        return _nn.charp_assign(self, value)

    def value(self):
        return _nn.charp_value(self)

    def cast(self):
        return _nn.charp_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _nn.charp_frompointer
    if _newclass:
        frompointer = staticmethod(_nn.charp_frompointer)
charp_swigregister = _nn.charp_swigregister
charp_swigregister(charp)

def charp_frompointer(t):
    return _nn.charp_frompointer(t)
charp_frompointer = _nn.charp_frompointer

class SparseLinear(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SparseLinear, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SparseLinear, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _nn.new_SparseLinear(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_setmethods__["weights"] = _nn.SparseLinear_weights_set
    __swig_getmethods__["weights"] = _nn.SparseLinear_weights_get
    if _newclass:
        weights = _swig_property(_nn.SparseLinear_weights_get, _nn.SparseLinear_weights_set)
    __swig_setmethods__["is_output_sparse"] = _nn.SparseLinear_is_output_sparse_set
    __swig_getmethods__["is_output_sparse"] = _nn.SparseLinear_is_output_sparse_get
    if _newclass:
        is_output_sparse = _swig_property(_nn.SparseLinear_is_output_sparse_get, _nn.SparseLinear_is_output_sparse_set)

    def init(self, arg2, arg3, arg4):
        return _nn.SparseLinear_init(self, arg2, arg3, arg4)
    __swig_destroy__ = _nn.delete_SparseLinear
    __del__ = lambda self: None
SparseLinear_swigregister = _nn.SparseLinear_swigregister
SparseLinear_swigregister(SparseLinear)

# This file is compatible with both classic and new-style classes.


